server:
  port: 9090

spring:
  application:
    name: stats-server
  datasource:
    url: jdbc:postgresql://localhost:5432/stats
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

logging:
  level:
    ru.practicum: debug
